# Application Name
spring.application.name=safetybackend

# Database Configuration (use Render PostgreSQL environment variables)
spring.datasource.url=jdbc:postgresql://dpg-d7dhr7pf9bms7385p160-a.singapore-postgres.render.com:5432/dangerousplaces
spring.datasource.username=dangerousplaces_user
spring.datasource.password=rm5fGP31DiEQ9Fy8pm0ESApZ9MH9zW8M
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port (Render assigns a dynamic port)
server.port=${PORT:8080}

# H2 Console (optional, can disable on production)
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

#GOOGLE API KEY
google.api.key=${GOOGLE_API_KEY}